common_dicts/common_dicts/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^slumber/', include('slumber.urls')),
)

flip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from frame import utils

from flip import views, public


admin.autodiscover()

settings_urls = [
    url(r'^phases_of_policy/$',
        views.SettingsPhasesOfPolicyView.as_view(),
        name='phases_of_policy'),

    url(r'^phases_of_policy/new/$',
        views.SettingsPhasesOfPolicyAddView.as_view(),
        name='phases_of_policy_edit'),

    url(r'^phases_of_policy/(?P<pk>\d+)/edit$',
        views.SettingsPhasesOfPolicyEditView.as_view(),
        name='phases_of_policy_edit'),

    url(r'^phases_of_policy/(?P<pk>\d+)/delete$',
        views.SettingsPhasesOfPolicyDeleteView.as_view(),
        name='phases_of_policy_delete'),

    url(r'^foresight_approaches/$',
        views.SettingsForesightApproachesView.as_view(),
        name='foresight_approaches'),

    url(r'^foresight_approaches/new$',
        views.SettingsForesightApproachesAddView.as_view(),
        name='foresight_approaches_edit'),

    url(r'^foresight_approaches/(?P<pk>\d+)/edit$',
        views.SettingsForesightApproachesEditView.as_view(),
        name='foresight_approaches_edit'),

    url(r'^foresight_approaches/(?P<pk>\d+)/delete$',
        views.SettingsForesightApproachesDeleteView.as_view(),
        name='foresight_approaches_delete'),

    url(r'^outcomes/$',
        views.SettingsOutcomesView.as_view(),
        name='outcomes'),

    url(r'^outcomes/new$',
        views.SettingsOutcomesAddView.as_view(),
        name='outcomes_edit'),

    url(r'^outcomes/(?P<pk>\d+)/edit$',
        views.SettingsOutcomesEditView.as_view(),
        name='outcomes_edit'),

    url(r'^outcomes/(?P<pk>\d+)/delete$',
        views.SettingsOutcomesDeleteView.as_view(),
        name='outcomes_delete'),

    url(r'^(?P<setting_name>[^/]+)/update_order$',
        views.SettingsUpdateOrder.as_view(),
        name='update_order'),
]

study_urls = [
    url(r'^(?P<study_type>[^/]+)/overview/$',
        views.StudiesView.as_view(),
        name='studies_overview'),

    url(r'^overview/$',
        views.StudiesView.as_view(),
        name='studies_overview'),

    url(r'^(?P<study_type>[^/]+)/new/$',
        views.StudyMetadataAddView.as_view(),
        name='study_metadata_add'),

    url(r'^new/$',
        views.StudyMetadataAddView.as_view(),
        name='study_metadata_add'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/edit$',
        views.StudyMetadataEditView.as_view(),
        name='study_metadata_edit'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/detail$',
        views.StudyMetadataDetailView.as_view(),
        name='study_metadata_detail'),

    url(r'^(?P<pk>\d+)/detail$',
        views.StudyMetadataDetailView.as_view(),
        name='study_metadata_detail'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/delete$',
        views.StudyDeleteView.as_view(),
        name='study_delete'),

    url(r'^(?P<pk>\d+)/delete$',
        views.StudyDeleteView.as_view(),
        name='study_delete'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/change/status$',
        views.StudyStatusEditView.as_view(),
        name='study_status_edit'),

    url(r'^(?P<pk>\d+)/change/status$',
        views.StudyStatusEditView.as_view(),
        name='study_status_edit'),

    url(r'^(?P<pk>\d+)/outcomes/detail$',
        views.StudyOutcomesDetailView.as_view(),
        name='study_outcomes_detail'),

    url(r'^(?P<pk>\d+)/outcomes/new$',
        views.StudyOutcomesAddView.as_view(),
        name='study_outcomes_add'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/detail$',
        views.StudyOutcomeDetailView.as_view(),
        name='study_outcome_detail'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/delete$',
        views.StudyOutcomeDeleteView.as_view(),
        name='study_outcome_delete'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/edit$',
        views.StudyOutcomeEditView.as_view(),
        name='study_outcome_edit'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/modal_edit$',
        views.StudyOutcomeEditModalView.as_view(),
        name='study_outcome_edit_modal'),

    url(r'^(?P<pk>\d+)/outcomes_section$',
        views.StudyOutcomesSectionView.as_view(),
        name='study_outcomes_section'),

]

public_urls = [
    url(r'^policy-cycle$', public.StudiesList.as_view(), name='studies_list'),
    url(r'^policy-cycle/(?P<pk>\d+)/detail$', public.StudiesDetail.as_view(),
        name='studies_detail'),
    url(r'^assessments$', public.AssessmentsList.as_view(),
        name='assessments_list'),
    url(r'^assessments/(?P<pk>\d+)/detail$', public.StudiesDetail.as_view(),
        name='assessments_detail'),
    url(r'^assessments/outcomes/(?P<outcome>\d+)$',
        public.OutcomesList.as_view(),
        name='assessments_outcomes'),
]

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name="home.html"),
        name='home_view'),

    url(r'^studies/entries/$',
        views.UserEntriesView.as_view(),
        name='user_entries'),

    url(r'^new/',
        views.StudyMetadataAddView.as_view(),
        name='add_new'),

    url(r'^studies/', include(study_urls)),

    url(r'^public/', include(public_urls, namespace='public')),

    url(r'^settings/', include(settings_urls, namespace='settings')),

    url(r'^_lastseencount/$', utils.get_objects_from_last_seen_count),

    url(r'^admin/', include(admin.site.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flip/models.py
from django.db.models import BooleanField, IntegerField
from django.db.models import CharField, URLField, TextField, FileField
from django.db.models import DateField, DateTimeField
from django.db.models import ManyToManyField, ForeignKey
from django.db.models import Model

from django.db.models.signals import pre_delete
from django.dispatch import receiver


class Study(Model):

    EEA = 'eea'
    OTHER = 'other'
    REQUESTED_BY_CHOICES = (
        (EEA, 'EEA'),
        (OTHER, 'Other'),
    )

    YES = 1
    NO = 0
    YES_NO_CHOICES = (
        ('', '----'),
        (YES, 'Yes'),
        (NO, 'No'),
    )

    POLICY = 'policy'
    NON_POLICY = 'non_policy'
    PURPOSE_CHOICES = (
        (POLICY, 'Support to policy'),
        (NON_POLICY, 'Non-policy (research, civil initiative, NGOs...'),
    )

    ACTIVITY = 'activity'
    ASSESSMENT = 'assessment'
    TYPE_CHOICES = (
        (ACTIVITY, 'Forward looking activity'),
        (ASSESSMENT, 'Assessment'),
    )

    BLOSSOM_CHOICES = (
        (YES, 'BLOSSOM study'),
        (NO, 'other study'),
    )

    draft = BooleanField(default=True)

    created_on = DateTimeField(auto_now_add=True)

    last_updated = DateTimeField(auto_now=True)

    user_id = CharField(max_length=64, blank=True)

    title = CharField(
        'title in English',
        max_length=255)

    languages = ManyToManyField(
        'Language',
        verbose_name='language of the study',
        through='StudyLanguage')

    url = URLField(blank=True)

    study_type = CharField(
        'I want to add a new',
        choices=TYPE_CHOICES,
        max_length=128,
        null=True,
    )

    blossom = IntegerField(
        'Approach to assessment',
        choices=BLOSSOM_CHOICES,
        default=NO,
    )

    requested_by = CharField(
        'who requested the study?',
        max_length=64,
        choices=REQUESTED_BY_CHOICES,
        blank=True
    )

    start_date = DateField('start date', null=True, blank=True)

    end_date = DateField('end date')

    lead_author = TextField('lead author')

    other = TextField(
        'other organisations/authors or contact persons',
        blank=True
    )

    purpose_and_target = CharField(
        'purpose and target audience',
        max_length=128,
        choices=PURPOSE_CHOICES,
        blank=True,
    )

    additional_information = TextField(
        'additional information',
        blank=True)

    phase_of_policy = ForeignKey(
        'PhasesOfPolicy',
        verbose_name='phases of policy cycle',
        null=True,
        blank=True)

    additional_information_phase = TextField(
        ('additional information about the application'),
        blank=True)

    foresight_approaches = ManyToManyField(
        'ForesightApproaches',
        verbose_name='foresight approaches used')

    additional_information_foresight = TextField(
        'additional information',
        blank=True)

    stakeholder_participation = BooleanField(
        'stakeholder participation',
        default=False)

    additional_information_stakeholder = TextField(
        'additional information about stakeholder involvement',
        blank=True)

    environmental_themes = ManyToManyField(
        'common.EnvironmentalTheme',
        verbose_name='topics',
        blank=True)

    geographical_scope = ForeignKey(
        'common.GeographicalScope',
        verbose_name='geographical scope',
        null=True,
        blank=True)

    countries = ManyToManyField(
        'common.Country',
        verbose_name='countries',
        blank=True)

    def __unicode__(self):
        return self.title


class Outcome(Model):

    study = ForeignKey(Study, related_name='outcomes')

    type_of_outcome = ForeignKey(
        'TypeOfOutcome',
        verbose_name='type of output',
        null=True,
        blank=True)

    document_title = CharField('title', max_length=255)

    text = TextField('text', null=True, blank=True)

    file_id = FileField(upload_to='outcomes', max_length=256, null=True,
                        blank=True, default='', verbose_name='File')

    def __unicode__(self):
        return self.document_title


class Language(Model):

    code = CharField(max_length=3, primary_key=True)
    title = CharField(max_length=32)

    def __unicode__(self):
        return self.title


class StudyLanguage(Model):

    language = ForeignKey(Language, verbose_name='language of the study')

    study = ForeignKey(Study)

    title = CharField('title in original language', max_length=255)

    def __unicode__(self):
        return self.title


class PhasesOfPolicy(Model):

    title = CharField(max_length=128)
    sort_id = IntegerField(default=0, null=True, blank=True)

    class Meta:
        ordering = ('sort_id',)

    def __unicode__(self):
        return self.title


class ForesightApproaches(Model):

    title = CharField(max_length=128)
    sort_id = IntegerField(default=0, null=True, blank=True)

    class Meta:
        ordering = ('sort_id',)

    def __unicode__(self):
        return self.title


class TypeOfOutcome(Model):
    TYPE_CHOICES = (
        ('all', 'All'),
        (Study.ACTIVITY, 'Forward looking activity'),
        (Study.ASSESSMENT, 'Assessment'),
    )

    title = CharField(max_length=256)
    blossom = BooleanField(default=False)
    doc_type = CharField(
        'Type',
        choices=TYPE_CHOICES,
        max_length=128,
        null=True,
        default='all'
    )
    sort_id = IntegerField(default=0, null=True, blank=True)

    class Meta:
        ordering = ('sort_id',)

    def __unicode__(self):
        return self.title


@receiver(pre_delete, sender=Outcome)
def outcome_delete_file(sender, instance, **kwargs):
    instance.file_id.delete(save=False)

flip/forms.py
from django.forms import BooleanField, ModelMultipleChoiceField
from django.forms import DateField, DateInput, ChoiceField, ModelChoiceField
from django.forms import ModelForm, Form
from django.forms.models import BaseInlineFormSet
from django.db.models import Q

from flip.models import (
    Study, Outcome, PhasesOfPolicy, ForesightApproaches, TypeOfOutcome
)
from flis_metadata.common.models import (
    Country, EnvironmentalTheme, GeographicalScope
)


class StudyMetadataForm(ModelForm):

    start_date = DateField(widget=DateInput(format='%d/%m/%Y'),
                           input_formats=('%d/%m/%Y',),
                           required=False)

    end_date = DateField(widget=DateInput(format='%d/%m/%Y'),
                         input_formats=('%d/%m/%Y',))

    draft = BooleanField(required=False)

    class Meta:
        model = Study
        fields = ('study_type', 'title', 'url', 'blossom',
                  'requested_by', 'start_date', 'end_date', 'draft',
                  'lead_author', 'other', 'purpose_and_target',
                  'additional_information', 'phase_of_policy',
                  'additional_information_phase', 'foresight_approaches',
                  'additional_information_foresight',
                  'stakeholder_participation',
                  'additional_information_stakeholder', 'environmental_themes',
                  'geographical_scope', 'countries')

    def __init__(self, *args, **kwargs):
        self.study = kwargs.get('instance', None)
        self.formset = kwargs.pop('formset', None)
        self.user_id = kwargs.pop('user_id', None)
        super(StudyMetadataForm, self).__init__(*args, **kwargs)
        self.fields['purpose_and_target'].required = True
        self.fields['geographical_scope'].required = True
        self.fields['foresight_approaches'].required = False
        self.fields['study_type'].required = False
        self.fields['geographical_scope'].queryset = (
            GeographicalScope.objects.filter(is_deleted=False))
        self.fields['countries'].queryset = (
            Country.objects.filter(is_deleted=False))
        self.fields['environmental_themes'].queryset = (
            EnvironmentalTheme.objects
            .filter(is_deleted=False)
            .order_by('title')
        )

    def clean(self):
        cleaned_data = super(StudyMetadataForm, self).clean()

        if self.study:
            cleaned_data['study_type'] = self.study.study_type

        if not self.formset.is_valid():
            self._errors['language'] = self.error_class(
                ['Language and original title are required.'])

        start_date_data = cleaned_data.get('start_date')
        blossom_data = cleaned_data.get('blossom')

        start_date = self.fields['start_date']

        if blossom_data == Study.YES:
            if start_date_data in start_date.empty_values:
                self._errors['start_date'] = self.error_class(
                    [start_date.error_messages['required']])
                cleaned_data.pop('start_date', None)

        geographical_scope_data = cleaned_data.get('geographical_scope')
        countries_data = cleaned_data.get('countries')
        countries = self.fields['countries']

        if (geographical_scope_data and
                geographical_scope_data.require_country):
            if len(countries_data) == 0:
                self._errors['countries'] = self.error_class(
                    [countries.error_messages['required']])
                cleaned_data.pop('countries', None)

        if (cleaned_data['study_type'] == 'activity' and
                not cleaned_data['phase_of_policy']):
            self._errors['phase_of_policy'] = self.error_class(
                [self.fields['phase_of_policy'].error_messages['required']])
            cleaned_data.pop('phase_of_policy', None)

        return cleaned_data

    def save(self):
        study = super(StudyMetadataForm, self).save(commit=False)
        study.user_id = self.user_id
        study.save()
        # save languages
        self.formset.save(study)
        self.save_m2m()
        return study


class BaseStudyLanguageInlineFormSet(BaseInlineFormSet):

    def __init__(self, *args, **kwargs):
        super(BaseStudyLanguageInlineFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

    def save(self, study):
        study_languages = super(BaseStudyLanguageInlineFormSet, self) \
            .save(commit=False)
        for study_language in study_languages:
            study_language.study = study
            study_language.save()
        return study_languages


class OutcomeForm(ModelForm):

    class Meta:
        model = Outcome
        exclude = ('study',)

    def __init__(self, *args, **kwargs):
        self.study = kwargs.pop('study', None)
        super(OutcomeForm, self).__init__(*args, **kwargs)
        self.fields['type_of_outcome'].queryset = (
            TypeOfOutcome.objects.filter(
                Q(doc_type=self.study.study_type) | Q(doc_type='all')))

    def save(self):
        outcome = super(OutcomeForm, self).save(commit=False)
        outcome.study = self.study
        outcome.save()
        return outcome


class FilterForm(Form):

    BLOSSOM_FILTER_CHOICES = (
        ('', 'All'),
        (Study.YES, 'Blossom'),
        (Study.NO, 'Non-Blossom'),
    )

    blossom = ChoiceField(
        choices=BLOSSOM_FILTER_CHOICES,
        label='Filter entries by')

    phase_of_policy = ModelChoiceField(
        queryset=PhasesOfPolicy.objects.all(),
        empty_label="All policy cycle steps")

    foresight_approaches = ModelMultipleChoiceField(
        queryset=ForesightApproaches.objects.all())

    my_entries = BooleanField()

flip/templates/study/_footer.html
<div class="form-group form-footer" style="margin-bottom: 0">

  {% if object and object.draft %}
    <button type="submit" name="draft" value="false"
          class="btn btn-primary">Publish</button>
  {% else %}
    <button type="submit" name="draft" value="false"
            class="btn btn-primary">{{ edit_mode|yesno:"Save,Publish" }}</button>
  {% endif %}

  {% if object %}
    {% if object.draft %}
      <button type="submit" name="draft" value="true"
              class="btn btn-default">Save as draft</button>
    {% endif %}
  {% else %}
    <button type="submit" name="draft" value="true"
            class="btn btn-default">Save as draft</button>
  {% endif %}

{% if cancel_url %}
  <a href="{{ cancel_url }}" class="btn btn-link" role="button">Cancel</a>
{% endif %}

</div>

flip/templates/study/_modal.html
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="modal-submit">Save</button>
                {% if show_submit_create %}
                  <button type="button" class="btn btn-primary" id="modal-submit-create">Save and create new</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>

flip/templates/study/_nav.html
{% load utils %}

<ul id="sub-menu" class="nav nav-pills">
  <li class={% active 'studies/[0-9]+/(detail|edit)$' %}>
    <a href="{% url 'study_metadata_detail' pk=study.pk %}">
      Metadata
    </a>
  </li>
</ul>

flip/templates/study/metadata_detail.html
{% extends '_layout.html' %}
{% load utils %}

{% block scripts %}

{% if open_popup %}
  <script>
    $(window).load(function(){
        var display_message = "You have successfully registered \" \
                               {{ study.title }} \". You can register outputs \
                               now, or do it later.";
        $('#add-output').data('message', display_message);
        $('#add-output').click();
        $('#add-output').data('message', '');
    });
  </script>
{% endif %}

{% endblock %}

{% block title %}

  {{ block.super }} -  Study Metadata

{% endblock %}

{% block content %}

  {% include '_studies_nav.html' %}
  <h2 class="page-title">{{ study.title }}</h2>
  {% include '_messages.html' %}

  {% can_edit_study study as can_edit_study %}
  {% if can_edit_study %}
    {% include '_bits/metadata_actions.html' %}
  {% endif %}

  <div class="row">
    <div class="col-sm-12">

      <table class="table table-detail table-bordered">

        <tr>
          <th>{{ form.title.label }}</th>
          <td>{{ study.title }}</td>
        </tr>

        {% if study.studylanguage_set.exists %}
          <tr>
            <th>Languages</th>
            <td>
              <ul class="list-unstyled">
                {% for study_lang in study.studylanguage_set.all %}
                  <li>
                    <div><b>{{ study_lang.language }}</b></div>
                    <div>- {{ study_lang.title }}</div>
                  </li>
                {% endfor %}
              </ul>
            </td>
          </tr>
        {% endif %}

        <tr>
          <th>{{ form.url.label }}</th>
          <td>{{ study.url }}</td>
        </tr>

        {% if study.study_type == 'assessment' %}
          <tr class="hd">
            <th colspan="2">Approach to assessment</th>
          </tr>

          <tr>
            <th>{{ form.blossom.label }}</th>
            <td>
              {% if study.blossom %}
                BLOSSOM
              {% else %}
                Other study
              {% endif %}
            </td>
          </tr>
        {% endif %}

        <tr class="hd">
          <th colspan="2">Timing</th>
        </tr>

        <tr>
          <th>{{ form.start_date.label }}</th>
          <td>{{ study.start_date|date:"d/m/Y" }}</td>
        </tr>

        <tr>
          <th>{{ form.end_date.label }}</th>
          <td>{{ study.end_date|date:"d/m/Y" }}</td>
        </tr>

        <tr class="hd">
          <th colspan="2">Scope of the {{ study.study_type }}</th>
        </tr>

        {% if study.study_type == 'assessment' %}
          <tr>
            <th>{{ form.environmental_themes.label }}</th>
            <td>
              <ul class="list-unstyled">
                {% for theme in study.environmental_themes.all %}
                  <li>{{ theme }}</li>
                {% empty %}
                  <li>None</li>
                {% endfor %}
              </ul>
            </td>
          </tr>
        {% endif %}

        <tr>
          <th>{{ form.geographical_scope.label }}</th>
          <td>{{ study.geographical_scope|default:'None' }}</td>
        </tr>

        {% if study.countries.exists %}
          <tr>
            <th>{{ form.countries.label }}</th>
            <td>
              <ul class="list-unstyled">
                {% for country in study.countries.all %}
                  <li>{{ country }}</li>
                {% endfor %}
              </ul>
          </tr>
        {% endif %}

        <tr class="hd">
          <th colspan="2">References and contact information</th>
        </tr>

        <tr>
          <th>{{ form.lead_author.label }}</th>
          <td>{{ study.lead_author }}</td>
        </tr>

        <tr>
          <th>{{ form.other.label }}</th>
          <td>{{ study.other }}</td>
        </tr>

        <tr class="hd">
          <th colspan="2">Purpose and target audience</th>
        </tr>

        <tr>
          <th>{{ form.purpose_and_target.label }}</th>
          <td>{{ study.get_purpose_and_target_display|default:'None' }}</td>
        </tr>

        <tr>
          <th>{{ form.additional_information.label }}</th>
          <td>{{ study.additional_information|default:'None' }}</td>
        </tr>

        {% if study.study_type == 'activity' %}
          <tr class="hd">
            <th colspan="2">Application of forward looking information in policy cycle</th>
          </tr>

          <tr>
            <th>{{ form.phase_of_policy.label }}</th>
            <td>{{ study.phase_of_policy|default:'None' }}</td>
          </tr>

          <tr>
            <th>{{ form.additional_information_phase.label }}</th>
            <td>{{ study.additional_information_phase|default:'None' }}</td>
          </tr>

          <tr class="hd">
            <th colspan="2">Methods and methodology used</th>
          </tr>

          <tr>
            <th>{{ form.foresight_approaches.label }}</th>
            <td>
              <ul class="list-unstyled">
                {% for foresight in study.foresight_approaches.all %}
                  <li>{{ foresight }}</li>
                {% empty %}
                  <li>None</li>
                {% endfor %}
              </ul>
            </td>
          </tr>

          <tr>
            <th>{{ form.additional_information_foresight.label }}</th>
            <td>{{ study.additional_information_foresight|default:'None' }}</td>
          </tr>

          <tr>
            <th>{{ form.stakeholder_participation.label }}</th>
            <td>
              {% if study.stakeholder_participation %}
                <i class="glyphicon glyphicon-ok"></i>
              {% else %}
                -
              {% endif %}
            </td>
          </tr>

          <tr>
            <th>{{ form.additional_information_stakeholder.label }}</th>
            <td>{{ study.additional_information_stakeholder|default:'None' }}</td>
          </tr>
        {% endif %}
      </table>
    </div>
  </div>

  {% if can_edit_study %}
    {% include '_bits/metadata_actions.html' %}
  {% endif %}
  <div class="row" id="outcomes"
      outcomes-url="{% url 'study_outcomes_section' study.id %}">
    {% include 'study/outcomes_section.html' %}
  </div> {# row #}

  {% include 'study/_modal.html' %}

{% endblock %}

flip/templates/study/outcome_add_form.html
<div id="confirmation-msg" class="alert alert-success hidden">
</div>

<div id="outcome-add" class="panel panel-default">
  <div class="panel-heading">
    <b>Add output</b> <br>
    <small>You can enter your text directly and/or attach relevant files</small>
  </div>
  <div class="panel-body">
      {% url 'study_outcomes_add' pk=object.pk as url %}
      <form action="{{ url }}" role="form" method="POST"
            id="study-modal-form"
            enctype="multipart/form-data"
            data-edit-form="true">
        {% include "study/_outcome_form.html" %}
      </form>
  </div> {# panel-body #}
</div> {# panel #}

flip/templates/study/outcome_confirm_delete.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} - Are you sure you want to delete "{{ outcome }}"?

{% endblock %}


{% block content %}

  <h3>Are you sure you want to delete "{{ outcome }}"?</h3>
  <br>
  <form method="POST">

    {% csrf_token %}

    <button class="btn btn-primary">Yes</button> or
    <a href="{% url 'study_metadata_detail' study.id %}">Cancel</a>

  </form>

{% endblock %}

flip/templates/study/outcome_edit.html
{% extends '_layout.html' %}
{% load utils %}

{% block title %}
  {{ block.super }} - Edit {{ outcome.document_title }}
{% endblock %}

{% block content %}
  {% include '_studies_nav.html' %}
  <div class="page-title">
      <h2>{{ study }}</h2>
  </div>

  {% include 'study/outcome_edit_form.html' with button=True %}

  <a href="{% url 'study_outcome_detail' study.id outcome.id %}"
     class="btn btn-link">Back</a>
{% endblock %}

flip/templates/study/outcome_edit_form.html
<div class="panel panel-default">
  <div class="panel-heading">
    <b>Edit {{ outcome.document_title }}</b> <br>
    <small>You can enter your text directly and/or attach relevant files</small>
  </div>
  <div class="panel-body">
      {% url 'study_outcome_edit' pk=study.pk outcome_pk=outcome.pk as url %}
      <form action="{{ url }}" method="POST"
            id="study-modal-form"
            enctype="multipart/form-data"
            data-edit-form="true">
        {% csrf_token %}
        {% include 'study/_outcome_form.html' %}
      </form>
  </div> {# panel-body #}
</div> {# panel #}

flip/templates/study/study_confirm_delete.html
{% extends '_layout.html' %}

{% block title %}

  {{ block.super }} - Are you sure you want to delete "{{ study }}"?

{% endblock %}


{% block content %}

  <h3>Are you sure you want to delete "{{ study }}"?</h3>
  <br>
  <form method="POST">

    {% csrf_token %}

    <button class="btn btn-primary">Yes</button>
    <a href="{% url 'study_metadata_detail' pk=study.pk %}">Cancel</a>
  </form>

{% endblock %}