common_dicts/common_dicts/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^slumber/', include('slumber.urls')),
)

flip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from frame import utils

from flip import views, public


admin.autodiscover()

settings_urls = [
    url(r'^phases_of_policy/$',
        views.SettingsPhasesOfPolicyView.as_view(),
        name='phases_of_policy'),

    url(r'^phases_of_policy/new/$',
        views.SettingsPhasesOfPolicyAddView.as_view(),
        name='phases_of_policy_edit'),

    url(r'^phases_of_policy/(?P<pk>\d+)/edit$',
        views.SettingsPhasesOfPolicyEditView.as_view(),
        name='phases_of_policy_edit'),

    url(r'^phases_of_policy/(?P<pk>\d+)/delete$',
        views.SettingsPhasesOfPolicyDeleteView.as_view(),
        name='phases_of_policy_delete'),

    url(r'^foresight_approaches/$',
        views.SettingsForesightApproachesView.as_view(),
        name='foresight_approaches'),

    url(r'^foresight_approaches/new$',
        views.SettingsForesightApproachesAddView.as_view(),
        name='foresight_approaches_edit'),

    url(r'^foresight_approaches/(?P<pk>\d+)/edit$',
        views.SettingsForesightApproachesEditView.as_view(),
        name='foresight_approaches_edit'),

    url(r'^foresight_approaches/(?P<pk>\d+)/delete$',
        views.SettingsForesightApproachesDeleteView.as_view(),
        name='foresight_approaches_delete'),

    url(r'^outcomes/$',
        views.SettingsOutcomesView.as_view(),
        name='outcomes'),

    url(r'^outcomes/new$',
        views.SettingsOutcomesAddView.as_view(),
        name='outcomes_edit'),

    url(r'^outcomes/(?P<pk>\d+)/edit$',
        views.SettingsOutcomesEditView.as_view(),
        name='outcomes_edit'),

    url(r'^outcomes/(?P<pk>\d+)/delete$',
        views.SettingsOutcomesDeleteView.as_view(),
        name='outcomes_delete'),

    url(r'^(?P<setting_name>[^/]+)/update_order$',
        views.SettingsUpdateOrder.as_view(),
        name='update_order'),
]

study_urls = [
    url(r'^(?P<study_type>[^/]+)/overview/$',
        views.StudiesView.as_view(),
        name='studies_overview'),

    url(r'^overview/$',
        views.StudiesView.as_view(),
        name='studies_overview'),

    url(r'^(?P<study_type>[^/]+)/new/$',
        views.StudyMetadataAddView.as_view(),
        name='study_metadata_add'),

    url(r'^new/$',
        views.StudyMetadataAddView.as_view(),
        name='study_metadata_add'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/edit$',
        views.StudyMetadataEditView.as_view(),
        name='study_metadata_edit'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/detail$',
        views.StudyMetadataDetailView.as_view(),
        name='study_metadata_detail'),

    url(r'^(?P<pk>\d+)/detail$',
        views.StudyMetadataDetailView.as_view(),
        name='study_metadata_detail'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/delete$',
        views.StudyDeleteView.as_view(),
        name='study_delete'),

    url(r'^(?P<pk>\d+)/delete$',
        views.StudyDeleteView.as_view(),
        name='study_delete'),

    url(r'^(?P<study_type>[^/]+)/(?P<pk>\d+)/change/status$',
        views.StudyStatusEditView.as_view(),
        name='study_status_edit'),

    url(r'^(?P<pk>\d+)/change/status$',
        views.StudyStatusEditView.as_view(),
        name='study_status_edit'),

    url(r'^(?P<pk>\d+)/outcomes/detail$',
        views.StudyOutcomesDetailView.as_view(),
        name='study_outcomes_detail'),

    url(r'^(?P<pk>\d+)/outcomes/new$',
        views.StudyOutcomesAddView.as_view(),
        name='study_outcomes_add'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/detail$',
        views.StudyOutcomeDetailView.as_view(),
        name='study_outcome_detail'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/delete$',
        views.StudyOutcomeDeleteView.as_view(),
        name='study_outcome_delete'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/edit$',
        views.StudyOutcomeEditView.as_view(),
        name='study_outcome_edit'),

    url(r'^(?P<pk>\d+)/outcomes/(?P<outcome_pk>\d+)/modal_edit$',
        views.StudyOutcomeEditModalView.as_view(),
        name='study_outcome_edit_modal'),

    url(r'^(?P<pk>\d+)/outcomes_section$',
        views.StudyOutcomesSectionView.as_view(),
        name='study_outcomes_section'),

]

public_urls = [
    url(r'^policy-cycle$', public.StudiesList.as_view(), name='studies_list'),
    url(r'^policy-cycle/(?P<pk>\d+)/detail$', public.StudiesDetail.as_view(),
        name='studies_detail'),
    url(r'^assessments$', public.AssessmentsList.as_view(),
        name='assessments_list'),
    url(r'^assessments/(?P<pk>\d+)/detail$', public.StudiesDetail.as_view(),
        name='assessments_detail'),
    url(r'^assessments/outcomes/(?P<outcome>\d+)$',
        public.OutcomesList.as_view(),
        name='assessments_outcomes'),
]

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name="home.html"),
        name='home_view'),

    url(r'^studies/entries/$',
        views.UserEntriesView.as_view(),
        name='user_entries'),

    url(r'^new/',
        views.StudyMetadataAddView.as_view(),
        name='add_new'),

    url(r'^studies/', include(study_urls)),

    url(r'^public/', include(public_urls, namespace='public')),

    url(r'^settings/', include(settings_urls, namespace='settings')),

    url(r'^_lastseencount/$', utils.get_objects_from_last_seen_count),

    url(r'^admin/', include(admin.site.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flip/views.py
import time

from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.http import Http404, HttpResponse
from django.db.models import Q

from flip import forms, models
from flip_auth.views import LoginRequiredMixin, EditPermissionRequiredMixin
from flip_auth.views import AdminPermissionRequiredMixin
from flip_auth.views import is_admin

from flis_metadata.common.models import GeographicalScope


class StudyLanguageFormMixin(object):

    def get_context_data(self, *args, **kwargs):
        data = super(StudyLanguageFormMixin, self) \
            .get_context_data(*args, **kwargs)
        data['formset'] = self.get_formset(self.request.POST)
        return data

    def get_formset(self, data=None):
        max_num = models.Language.objects.count()
        extra = 0 if self.object else 1
        StudyLanguageInlineFormSet = inlineformset_factory(
            models.Study, models.StudyLanguage,
            formset=forms.BaseStudyLanguageInlineFormSet,
            fields=('language', 'title'),
            extra=extra, max_num=max_num, validate_max=True, can_delete=True)

        if data:
            return StudyLanguageInlineFormSet(data, instance=self.object)
        else:
            return StudyLanguageInlineFormSet(instance=self.object)

    def get_form_kwargs(self):
        kwargs = super(StudyLanguageFormMixin, self).get_form_kwargs()
        kwargs['formset'] = self.get_formset(self.request.POST)
        kwargs['user_id'] = self.request.user_id
        return kwargs


class ParametersMixin(object):
    def dispatch(self, request, **kwargs):
        study_type = kwargs.get('study_type', None)
        pk = kwargs.get('pk', None)

        if study_type:
            if study_type not in dict(models.Study.TYPE_CHOICES).keys():
                raise Http404
            self.study_type = study_type
        if pk:
            self.pk = pk
        return super(ParametersMixin, self).dispatch(request, **kwargs)


class StudyMetadataAddView(LoginRequiredMixin,
                           EditPermissionRequiredMixin,
                           StudyLanguageFormMixin,
                           SuccessMessageMixin,
                           ParametersMixin,
                           generic.CreateView):

    model = models.Study
    form_class = forms.StudyMetadataForm
    template_name = 'study/study_add.html'
    success_message = 'The study was successfully updated'

    def get_success_url(self):
        kwargs = {'pk': self.object.pk,
                  'study_type': self.object.study_type}
        return reverse('study_metadata_detail', kwargs=kwargs)

    def get_context_data(self, **kwargs):
        self.request.session['first_time_edit'] = True
        require_country = [str(scope.id) for scope in GeographicalScope.
                           objects.filter(require_country=True)]
        context = {'cancel_url': reverse('studies_overview'),
                   'require_country': require_country}

        if hasattr(self, 'study_type'):
            context['study_type'] = self.study_type

        context.update(kwargs)
        return super(StudyMetadataAddView, self).get_context_data(**context)


class StudyMetadataDetailView(LoginRequiredMixin,
                              ParametersMixin,
                              generic.DetailView):

    model = models.Study
    template_name = 'study/metadata_detail.html'

    def get_context_data(self, **kwargs):
        context = {
            'form': forms.StudyMetadataForm(),
            'show_submit_create': True,
        }
        if 'first_time_edit' in self.request.session:
            context['open_popup'] = True
            self.request.session.clear()
        context.update(kwargs)
        return super(StudyMetadataDetailView, self).get_context_data(**context)


class StudyOutcomesSectionView(LoginRequiredMixin,
                               generic.DetailView):
    model = models.Study
    template_name = 'study/outcomes_section.html'


class StudyMetadataEditView(LoginRequiredMixin,
                            EditPermissionRequiredMixin,
                            StudyLanguageFormMixin,
                            SuccessMessageMixin,
                            ParametersMixin,
                            generic.UpdateView):

    model = models.Study
    form_class = forms.StudyMetadataForm
    template_name = 'study/study_edit.html'
    success_message = 'The study was successfully updated'

    def get_queryset(self, queryset=None):
        if is_admin(self.request):
            return self.model._default_manager.all()._clone()
        else:
            return (
                self.model._default_manager
                .filter(user_id=self.request.user_id)
                ._clone()
            )

    def get_context_data(self, **kwargs):
        require_country = [str(scope.id) for scope in GeographicalScope.
                           objects.filter(require_country=True)]
        context = {'cancel_url': reverse('study_metadata_detail',
                                         kwargs={'pk': self.object.pk}),
                   'edit_mode': True,
                   'require_country': require_country}
        context.update(kwargs)
        return super(StudyMetadataEditView, self).get_context_data(**context)

    def get_success_url(self):
        kwargs = {'pk': self.object.pk}
        if hasattr(self, 'study_type'):
            kwargs['study_type'] = self.study_type
        return reverse('study_metadata_detail', kwargs=kwargs)


class StudyDeleteView(LoginRequiredMixin,
                      EditPermissionRequiredMixin,
                      generic.DeleteView):

    model = models.Study
    template_name = 'study/study_confirm_delete.html'

    def get_success_url(self):
        return reverse('studies_overview')


class StudyStatusEditView(LoginRequiredMixin,
                          EditPermissionRequiredMixin,
                          generic.View):

    def post(self, request, pk, study_type):
        study = get_object_or_404(models.Study, pk=pk)
        study.draft = not study.draft
        study.save()
        return redirect(reverse('study_metadata_detail',
                                kwargs={'pk': pk,
                                        'study_type': study_type}))


class StudyOutcomesDetailView(LoginRequiredMixin,
                              generic.DetailView):

    model = models.Study
    template_name = 'study/outcomes_detail.html'

    def get_object(self):
        return get_object_or_404(models.Study, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = {'form': forms.OutcomeForm(study=self.object)}
        context.update(kwargs)
        return super(StudyOutcomesDetailView, self).get_context_data(**context)


class StudyOutcomesAddView(LoginRequiredMixin,
                           EditPermissionRequiredMixin,
                           SuccessMessageMixin,
                           generic.CreateView):

    model = models.Outcome
    form_class = forms.OutcomeForm
    template_name = 'study/outcome_add_form.html'

    def get_object(self):
        if getattr(self, 'study', None):
            return self.study
        if is_admin(self.request):
            study = get_object_or_404(models.Study, pk=self.kwargs['pk'])
        else:
            study = get_object_or_404(models.Study, pk=self.kwargs['pk'],
                                      user_id=self.request.user_id)

        study = get_object_or_404(models.Study, pk=self.kwargs['pk'])
        self.study = study
        return study

    def get_form_kwargs(self):
        kwargs = super(StudyOutcomesAddView, self).get_form_kwargs()
        kwargs['study'] = self.get_object()
        return kwargs

    def get_success_url(self):
        return reverse('study_outcomes_detail',
                       kwargs={'pk': self.get_object().pk})

    def get_success_message(self, cleaned_data):
        return u'{document_title} was successfully added'.format(
            **cleaned_data)


class StudyOutcomeDeleteView(LoginRequiredMixin,
                             EditPermissionRequiredMixin,
                             generic.DeleteView):

    model = models.Outcome
    pk_url_kwarg = 'outcome_pk'
    template_name = 'study/outcome_confirm_delete.html'

    def dispatch(self, request, pk, outcome_pk):
        self.study = get_object_or_404(models.Study, pk=pk)
        return super(StudyOutcomeDeleteView, self).dispatch(request, pk)

    def get_queryset(self, queryset=None):
        if is_admin(self.request):
            return self.model._default_manager.all()._clone()
        else:
            return (
                self.model._default_manager
                .filter(study__user_id=self.request.user_id)
                ._clone()
            )

    def get_success_url(self):
        return reverse('study_metadata_detail', kwargs={'pk': self.study.pk})

    def get_context_data(self, **kwargs):
        context = {'study': self.study}
        context.update(kwargs)
        return super(StudyOutcomeDeleteView, self).get_context_data(**context)


class StudyOutcomeDetailView(LoginRequiredMixin,
                             generic.DetailView):

    model = models.Outcome
    pk_url_kwarg = 'outcome_pk'
    template_name = 'study/outcome_detail.html'

    def dispatch(self, request, pk, outcome_pk):
        self.study = get_object_or_404(models.Study, pk=pk)
        return super(StudyOutcomeDetailView, self).dispatch(request, pk)

    def get_context_data(self, **kwargs):
        context = {'study': self.study,
                   'back_url': reverse('study_metadata_detail',
                                       kwargs={'pk': self.study.pk})}
        context.update(kwargs)

flip/templates/settings/environmental_themes.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} -  Settings (Environmental Themes)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% url 'settings:environmental_themes_edit' as add_url %}
  <div class="actions">
    <a href="{{ add_url }}" class="btn btn-primary">Add new theme</a>
  </div>

  {% if object_list %}

    <table id="settings" width="100%"
           class="table table-condensed table-bordered table-hover">

      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
          {% url 'settings:environmental_themes_edit' pk=object.pk as edit_url %}
          <tr>
            <td>
              <a href="{{ edit_url }}">{{ object.title }}</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>

    </table>

  {% endif %}


{% endblock%}

flip/templates/settings/environmental_themes_confirm_delete.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} - Are you sure you want to delete "{{ object }}"?

{% endblock %}


{% block content %}

  <h3>Are you sure you want to delete "{{ object }}"?</h3>
  <br>
  <form method="POST">

    {% csrf_token %}

    <button class="btn btn-primary">Yes</button>
    <a href="{% url 'settings:environmental_themes_edit' pk=object.pk %}">
      Cancel</a>
  </form>

{% endblock %}

flip/templates/settings/environmental_themes_edit.html
{% extends '_layout.html' %}
{% load widget_tweaks %}


{% block title %}

  {{ block.super }} -  Settings (Environmental Themes)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% if object %}
    {% url 'settings:environmental_themes_delete' pk=object.pk as delete_url %}
    <div class="actions">
      <a href="{{ delete_url }}" class="btn btn-danger">Delete</a>
    </div>
  {% endif %}

  <form id="environmental-themes-form" method="POST" role="form">

    {% csrf_token %}

    <div class="form-group">
      <div class="row">
        <div class="col-md-9">
          {{ form.title.label_tag }}
          {% if form.title.field.required %}
            <span class="required">*</span>
          {% endif %}

          {% render_field form.title class='form-control' %}
          {% if form.title.errors %}
            <p class="text-danger">
              <small>{{ form.title.errors.0 }}</small></p>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-group form-footer" style="margin-bottom: 0">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>


  </form>

{% endblock %}

flip/templates/settings/foresight_approaches.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} -  Settings (Foresight Approaches)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% url 'settings:foresight_approaches_edit' as add_url %}
  <div class="actions">
    <a href="{{ add_url }}" class="btn btn-primary">Add new foresight</a>
  </div>

  {% if object_list %}

    <table id="settings" width="100%"
           class="table table-condensed table-bordered table-hover sortable"
           data-url="{% url 'settings:update_order' setting_name='approach' %}">

      <thead>
        <tr>
          <th class="handler"></th>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
          {% url 'settings:foresight_approaches_edit' pk=object.pk as edit_url %}
          <tr id="items-{{ object.pk }}">
            <td class="handler" width="20">
              <span class="glyphicon glyphicon-align-justify"></span>
            </td>
            <td>
              <a href="{{ edit_url }}">{{ object.title }}</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>

    </table>

  {% endif %}


{% endblock%}

flip/templates/settings/foresight_approaches_confirm.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} - Are you sure you want to delete "{{ object }}"?

{% endblock %}


{% block content %}

  <h3>Are you sure you want to delete "{{ object }}"?</h3>
  <br>
  <form method="POST">

    {% csrf_token %}

    <button class="btn btn-primary">Yes</button>
    <a href="{% url 'settings:foresight_approaches_edit' pk=object.pk %}">
      Cancel</a>
  </form>

{% endblock %}

flip/templates/settings/foresight_approaches_edit.html
{% extends '_layout.html' %}
{% load widget_tweaks %}


{% block title %}

  {{ block.super }} -  Settings (Foresight Approaches)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% if object %}
    {% url 'settings:foresight_approaches_delete' pk=object.pk as delete_url %}
    <div class="actions">
      <a href="{{ delete_url }}" class="btn btn-danger">Delete</a>
    </div>
  {% endif %}

  <form id="foresigh-approaches-form" method="POST" role="form">

    {% csrf_token %}

    <div class="form-group">
      <div class="row">
        <div class="col-md-9">
          {{ form.title.label_tag }}
          {% if form.title.field.required %}
            <span class="required">*</span>
          {% endif %}

          {% render_field form.title class='form-control' %}
          {% if form.title.errors %}
            <p class="text-danger">
              <small>{{ form.title.errors.0 }}</small></p>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-group form-footer" style="margin-bottom: 0">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>


  </form>

{% endblock %}

flip/templates/settings/geographical_scopes.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} -  Settings (Geographical Scopes)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% url 'settings:geographical_scopes_edit' as add_url %}
  <div class="actions">
    <a href="{{ add_url }}" class="btn btn-primary">Add new scope</a>
  </div>

  {% if object_list %}

    <table id="settings" width="100%"
           class="table table-condensed table-bordered table-hover">

      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
          {% url 'settings:geographical_scopes_edit' pk=object.pk as edit_url %}
          <tr>
            <td>
              <a href="{{ edit_url }}">{{ object.title }}</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>

    </table>

  {% endif %}


{% endblock%}

flip/templates/settings/geographical_scopes_confirm_delete.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} - Are you sure you want to delete "{{ object }}"?

{% endblock %}


{% block content %}

  <h3>Are you sure you want to delete "{{ object }}"?</h3>
  <br>
  <form method="POST">

    {% csrf_token %}

    <button class="btn btn-primary">Yes</button>
    <a href="{% url 'settings:geographical_scopes_edit' pk=object.pk %}">
      Cancel</a>
  </form>

{% endblock %}

flip/templates/settings/outcomes.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} -  Settings (Outputs)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% url 'settings:outcomes_edit' as add_url %}
  <div class="actions">
    <a href="{{ add_url }}" class="btn btn-primary">Add new output</a>
  </div>

  {% if object_list %}

    <table id="settings" width="100%"
           class="table table-condensed table-bordered table-hover sortable"
           data-url="{% url 'settings:update_order' setting_name='outcome' %}">

      <thead>
        <tr>
          <th class="handler"></th>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
          {% url 'settings:outcomes_edit' pk=object.pk as edit_url %}
          <tr id="items-{{ object.pk }}">
            <td class="handler" width="20">
              <span class="glyphicon glyphicon-align-justify"></span>
            </td>
            <td>
              <a href="{{ edit_url }}">
                {{ object.title }} ({{ object.doc_type|capfirst }})
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>

    </table>

  {% endif %}


{% endblock%}

flip/templates/settings/outcomes_edit.html
{% extends '_layout.html' %}
{% load widget_tweaks %}


{% block title %}

  {{ block.super }} -  Settings (Outputs)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% if object %}
    {% url 'settings:outcomes_delete' pk=object.pk as delete_url %}
    <div class="actions">
      <a href="{{ delete_url }}" class="btn btn-danger">Delete</a>
    </div>
  {% endif %}

  <form id="outcomes-form" method="POST" role="form">

    {% csrf_token %}

    <div class="form-group">
      <div class="row">
        <div class="col-md-9">
          {{ form.title.label_tag }}
          {% if form.title.field.required %}
            <span class="required">*</span>
          {% endif %}

          {% render_field form.title class='form-control' %}
          {% if form.title.errors %}
            <p class="text-danger">
              <small>{{ form.title.errors.0 }}</small></p>
          {% endif %}
        </div>
        <div class="col-md-9">
          {{ form.doc_type.label_tag }}
          {% if form.doc_type.required %}
            <span class="required">*</span>
          {% endif %}

          {% render_field form.doc_type class='form-control' %}
          {% if form.doc_type.errors %}
            <p class="text-danger">
              <small>{{ form.doc_type.errors.0 }}</small></p>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-group form-footer" style="margin-bottom: 0">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>

  </form>

{% endblock %}

flip/templates/settings/phases_of_policy.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} -  Settings (Phases of Policy)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% url 'settings:phases_of_policy_edit' as add_url %}
  <div class="actions">
    <a href="{{ add_url }}" class="btn btn-primary">Add new policy</a>
  </div>

  {% if object_list %}

    <table id="settings" width="100%"
           class="table table-condensed table-bordered table-hover">

      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
          {% url 'settings:phases_of_policy_edit' pk=object.pk as edit_url %}
          <tr>
            <td>
              <a href="{{ edit_url }}">{{ object.title }}</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>

    </table>

  {% endif %}

{% endblock %}

flip/templates/settings/phases_of_policy_edit.html
{% extends '_layout.html' %}
{% load widget_tweaks %}


{% block title %}

  {{ block.super }} -  Settings (Phases of Policy)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}


  <form id="phases-of-policy-form" method="POST" role="form">

    {% csrf_token %}

    <div class="form-group">
      <div class="row">
        <div class="col-md-9">
          {{ form.title.label_tag }}
          {% if form.title.field.required %}
            <span class="required">*</span>
          {% endif %}

          {% render_field form.title class='form-control' %}
          {% if form.title.errors %}
            <p class="text-danger">
              <small>{{ form.title.errors.0 }}</small></p>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-group form-footer" style="margin-bottom: 0">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>


  </form>

{% endblock %}

flip/templates/settings/policy.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} -  Settings (Phases of Policy)

{% endblock %}


{% block content %}

  {% include '_messages.html' %}
  {% include '_studies_nav.html' %}

  {% url 'settings:phases_of_policy_edit' as add_url %}
  <div class="actions">
    <a href="{{ add_url }}" class="btn btn-primary">Add new policy</a>
  </div>

  {% if object_list %}

    <table id="settings" width="100%"
           class="table table-condensed table-bordered table-hover sortable"
           data-url="{% url 'settings:update_order' setting_name='policy' %}">

      <thead>
        <tr>
          <th class="handler"></th>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
          {% url 'settings:phases_of_policy_edit' pk=object.pk as edit_url %}
          <tr id="items-{{ object.pk }}">
            <td class="handler" width="20">
              <span class="glyphicon glyphicon-align-justify"></span>
            </td>
            <td>
              <a href="{{ edit_url }}">{{ object.title }}</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>

    </table>

  {% endif %}

{% endblock %}

flip/templates/settings/policy_confirm_delete.html
{% extends '_layout.html' %}


{% block title %}

  {{ block.super }} - Are you sure you want to delete "{{ object }}"?

{% endblock %}


{% block content %}

  <h3>Are you sure you want to delete "{{ object }}"?</h3>
  <br>
  <form method="POST">

    {% csrf_token %}

    <button class="btn btn-primary">Yes</button>
    <a href="{% url 'settings:phases_of_policy_edit' pk=object.pk %}">
      Cancel</a>
  </form>

{% endblock %}